# Generated by Django 4.0.8 on 2023-11-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qurancloud', '0002_alter_edition_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='surah',
            name='numberOfAyahs',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
