# Generated by Django 4.0.8 on 2023-11-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qurancloud', '0003_surah_numberofayahs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surah',
            name='edition',
        ),
    ]
