# Generated by Django 4.0.8 on 2023-11-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qurancloud', '0005_remove_surah_ayahs_ayah_audio_ayah_audio_secondary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayah',
            name='audio',
            field=models.URLField(blank=True, null=True),
        ),
    ]
