# Generated by Django 4.0.8 on 2023-11-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qurancloud', '0006_alter_ayah_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayah',
            name='audio',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='ayah',
            name='audio_secondary',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
